import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { useData } from '../context/DataContext'
import { useToast } from '../context/ToastContext'
import TaskModal from '../components/modals/TaskModal'
import EventModal from '../components/modals/EventModal'
import EmptyState from '../components/common/EmptyState'

const DASH_EVENT_BADGES = ['pill-blue', 'pill-orange', 'pill-red']

const PORTFOLIO_TILES = [
  { icon: 'fa-trophy', label: 'Sports', count: '12 Tasks' },
  { icon: 'fa-laptop-code', label: 'Technical', count: '14 Tasks' },
  { icon: 'fa-masks-theater', label: 'Cultural', count: '10 Tasks' },
  { icon: 'fa-hand-holding-heart', label: 'Social Responsibility', count: '9 Tasks' },
  { icon: 'fa-bullhorn', label: 'PR & Media', count: '7 Tasks' },
  { icon: 'fa-people-group', label: 'Student Welfare', count: '8 Tasks' },
  { icon: 'fa-briefcase', label: 'T&P', count: '6 Tasks' },
  { icon: 'fa-user-group', label: "Women's Rep.", count: '5 Tasks' }
]

// Static in the original -- not backend-driven, copied verbatim.
const ANNOUNCEMENTS = [
  { text: 'Student Council Orientation Program', date: '23 Aug, 2026' },
  { text: 'Submission of Event Proposals', date: '22 Aug, 2026' },
  { text: 'Independence Day Celebration', date: '15 Aug, 2026' }
]

function escapeHtml(value: unknown = ''): string {
  return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[c] as string))
}

export default function Dashboard() {
  const { user } = useAuth()
  const { tasks, events, meetings, grievances } = useData()
  const showToast = useToast()
  const navigate = useNavigate()
  const [taskModalOpen, setTaskModalOpen] = useState(false)
  const [eventModalOpen, setEventModalOpen] = useState(false)

  const stats = useMemo(() => {
    const total = tasks.length
    const norm = (s?: string) => String(s || '').toLowerCase().replace(/\s+/g, ' ')
    const pending = tasks.filter((t) => norm(t.status) === 'pending').length
    const completed = tasks.filter((t) => norm(t.status) === 'completed').length
    const inProgress = tasks.filter((t) => norm(t.status) === 'in progress').length
    const overdue = tasks.filter((t) => norm(t.status) === 'overdue').length
    const pct = (n: number) => (total ? Math.round((n / total) * 100) + '%' : '0%')
    return { total, pending, completed, inProgress, overdue, pct }
  }, [tasks])

  const dateLabel = useMemo(() => new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }), [])

  const generateMonthlyReport = () => {
    const t = tasks,
      e = events,
      m = meetings,
      f: any[] = [],
      g = grievances
    const w = window.open('', '_blank')
    if (!w) {
      showToast('Please allow pop-ups for report generation.', 'error')
      return
    }
    const done = t.filter((x) => x.status === 'Completed').length
    const approved = f.filter((x) => x.status === 'Approved').length
    const resolved = g.filter((x) => ['Resolved', 'Closed', 'resolved', 'closed'].includes(x.status)).length
    w.document.write(`<html><head><title>ASTRA SCMS Monthly Council Report</title><style>body{font-family:Arial;padding:34px;color:#3b1725}h1,h2{color:#7a1f3d}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.k{padding:14px;background:#fbf4ec;border:1px solid #e8d8cf;border-radius:10px}.k b{display:block;font-size:22px;color:#7a1f3d}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border:1px solid #ddd;padding:8px;font-size:11px}th{background:#f3e4d7}</style></head><body><h1>ASTRA • ORBITA MINI</h1><h2>Monthly Student Council Report</h2><p>${new Date().toLocaleString('en-IN', { month: 'long', year: 'numeric' })}</p><div class="grid"><div class="k"><b>${t.length}</b>Tasks</div><div class="k"><b>${done}</b>Completed</div><div class="k"><b>${e.length}</b>Events</div><div class="k"><b>${m.length}</b>Meetings</div><div class="k"><b>${f.length}</b>Finance Requests</div><div class="k"><b>${approved}</b>Approved Finance</div><div class="k"><b>${g.length}</b>Grievances</div><div class="k"><b>${resolved}</b>Resolved</div></div><h2>Task Summary</h2><table><tr><th>Task</th><th>Assignee</th><th>Status</th><th>Priority</th></tr>${t
      .map((x) => `<tr><td>${escapeHtml(x.title || '')}</td><td>${escapeHtml(x.assigned_name || '')}</td><td>${escapeHtml(x.status || '')}</td><td>${escapeHtml(x.priority || '')}</td></tr>`)
      .join('')}</table><p>Generated by ASTRA • ORBITA MINI. Use Print → Save as PDF.</p><script>window.onload=()=>window.print()<\/script></body></html>`)
    w.document.close()
  }

  return (
    <div id="view-dashboard" className="view-section scms-original-dashboard">
      <div className="dash-welcome-row">
        <div className="dash-welcome">
          <div className="dash-eyebrow">
            <span className="live-dot" /> COUNCIL COMMAND CENTER
          </div>
          <h1>
            Welcome back, <span id="dash-user-name">{user?.name || 'Council Member'}</span>! <span className="wave">👋</span>
          </h1>
          <p id="dash-role-subtitle">{(user?.role_name || 'Council Member') + ' Dashboard'}</p>
        </div>
        <div className="dash-date">
          <i className="fa-regular fa-calendar" />
          <span id="dash-date-label">{dateLabel}</span>
        </div>
      </div>

      <div className="dash-layout">
        <section className="dash-main-col">
          <div className="dash-kpi-grid">
            <div className="dash-kpi">
              <div className="dash-kpi-icon">
                <i className="fa-solid fa-clipboard-check" />
              </div>
              <div>
                <span>Total Tasks</span>
                <strong id="stat-total">{stats.total}</strong>
              </div>
              <button onClick={() => navigate('/tasks')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div className="dash-kpi">
              <div className="dash-kpi-icon">
                <i className="fa-solid fa-hourglass-half" />
              </div>
              <div>
                <span>Pending Tasks</span>
                <strong id="stat-pending">{stats.pending}</strong>
              </div>
              <button onClick={() => navigate('/tasks')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div className="dash-kpi success">
              <div className="dash-kpi-icon">
                <i className="fa-solid fa-chart-line" />
              </div>
              <div>
                <span>Completed Tasks</span>
                <strong id="stat-completed">{stats.completed}</strong>
              </div>
              <button onClick={() => navigate('/tasks')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div className="dash-kpi danger">
              <div className="dash-kpi-icon">
                <i className="fa-regular fa-clock" />
              </div>
              <div>
                <span>Overdue Tasks</span>
                <strong id="stat-overdue">{stats.overdue}</strong>
              </div>
              <button onClick={() => navigate('/tasks')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
          </div>

          <div className="dash-two-col">
            <div className="dash-card task-overview-card">
              <div className="dash-card-head">
                <h3>Task Overview</h3>
                <button onClick={() => navigate('/tasks')}>
                  View all tasks <i className="fa-solid fa-arrow-right" />
                </button>
              </div>
              <div className="task-overview-body">
                <div className="donut-large">
                  <div>
                    <strong id="dash-donut-total">{stats.total}</strong>
                    <span>Total</span>
                  </div>
                </div>
                <div className="task-legend">
                  <div>
                    <i className="legend-dot pending" />
                    <span>Pending</span>
                    <b id="legend-pending">{stats.pending}</b>
                    <small id="legend-pending-pct">{stats.pct(stats.pending)}</small>
                  </div>
                  <div>
                    <i className="legend-dot progress" />
                    <span>In Progress</span>
                    <b id="legend-progress">{stats.inProgress}</b>
                    <small id="legend-progress-pct">{stats.pct(stats.inProgress)}</small>
                  </div>
                  <div>
                    <i className="legend-dot completed" />
                    <span>Completed</span>
                    <b id="legend-completed">{stats.completed}</b>
                    <small id="legend-completed-pct">{stats.pct(stats.completed)}</small>
                  </div>
                  <div>
                    <i className="legend-dot overdue" />
                    <span>Overdue</span>
                    <b id="legend-overdue">{stats.overdue}</b>
                    <small id="legend-overdue-pct">{stats.pct(stats.overdue)}</small>
                  </div>
                </div>
              </div>
            </div>

            <div className="dash-card">
              <div className="dash-card-head">
                <h3>Upcoming Events</h3>
                <button onClick={() => navigate('/events')}>
                  View all events <i className="fa-solid fa-arrow-right" />
                </button>
              </div>
              <div id="dash-events-container" className="dash-event-list">
                {events.length === 0 && <div className="empty-state">No upcoming events.</div>}
                {events.slice(0, 3).map((e, i) => {
                  const raw = String(e.date || '')
                  const d = new Date(raw)
                  const valid = !isNaN(d.getTime())
                  const day = valid ? d.getDate() : ''
                  const mon = valid ? d.toLocaleString('en-IN', { month: 'short' }).toUpperCase() : 'TBA'
                  return (
                    <div className="dash-event" key={e.id}>
                      <div className="dash-event-date">
                        <b>{day || '—'}</b>
                        <small>{mon}</small>
                      </div>
                      <div>
                        <span className="dash-event-title">{e.title || 'Untitled event'}</span>
                        <span className="dash-event-sub">{e.type || e.location || 'Council Department'}</span>
                      </div>
                      <span className={`pill-badge ${DASH_EVENT_BADGES[i % 3]}`}>Upcoming</span>
                    </div>
                  )
                })}
              </div>
            </div>
          </div>

          <div className="dash-card portfolio-card">
            <div className="dash-card-head">
              <h3>Portfolio Activity</h3>
              <button onClick={() => navigate('/teams')}>
                View full report <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div className="portfolio-grid">
              {PORTFOLIO_TILES.map((tile) => (
                <button key={tile.label} onClick={() => navigate('/teams')}>
                  <i className={`fa-solid ${tile.icon}`} />
                  <span>
                    {tile.label}
                    <small>{tile.count}</small>
                  </span>
                </button>
              ))}
            </div>
          </div>
        </section>

        <div className="dash-right-col">
          <div className="dash-card">
            <div className="dash-card-head">
              <h3>Announcements</h3>
              <button onClick={() => showToast('Announcements are part of Phase 2.')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div className="announcement-list">
              {ANNOUNCEMENTS.map((a) => (
                <div key={a.text}>
                  <i className="fa-solid fa-bullhorn" />
                  <span>
                    {a.text}
                    <small>{a.date}</small>
                  </span>
                </div>
              ))}
            </div>
          </div>

          <div className="dash-card mytasks-card">
            <div className="dash-card-head">
              <h3>My Tasks</h3>
              <button onClick={() => navigate('/tasks')}>
                View all <i className="fa-solid fa-arrow-right" />
              </button>
            </div>
            <div id="dash-my-tasks" className="mytask-list">
              {tasks.length === 0 && <EmptyState icon="fa-clipboard-check" title="No tasks assigned" text="Create a task to start tracking council work." />}
              {tasks.slice(0, 4).map((t, i) => (
                <div className="dash-mytask" key={t.id}>
                  <span className="num">{i + 1}</span>
                  <div>
                    <strong>{t.title || 'Untitled task'}</strong>
                    <small>Due: {t.due_date || 'TBA'}</small>
                  </div>
                  <span className="dash-priority">{t.priority || 'Medium'}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="dash-card quick-card">
            <div className="dash-card-head">
              <h3>Quick Actions</h3>
            </div>
            <div className="quick-grid">
              {user?.role !== 'committee_member' && (
                <button id="btn-show-task" onClick={() => setTaskModalOpen(true)}>
                  <i className="fa-solid fa-plus" />
                  Assign Task
                </button>
              )}
              {user?.role !== 'committee_member' && (
                <button id="btn-show-event" onClick={() => setEventModalOpen(true)}>
                  <i className="fa-regular fa-calendar" />
                  Create Event
                </button>
              )}
              <button onClick={() => navigate('/members')}>
                <i className="fa-solid fa-users" />
                Add Member
              </button>
              <button onClick={() => showToast('Announcements are part of Phase 2.')}>
                <i className="fa-solid fa-bullhorn" />
                New Announcement
              </button>
              <button onClick={() => showToast('Document uploads are part of Phase 2.')}>
                <i className="fa-solid fa-folder-open" />
                Upload Document
              </button>
              <button onClick={generateMonthlyReport}>
                <i className="fa-solid fa-chart-column" />
                Monthly Report
              </button>
            </div>
          </div>
        </div>
      </div>

      <TaskModal open={taskModalOpen} onClose={() => setTaskModalOpen(false)} />
      <EventModal open={eventModalOpen} onClose={() => setEventModalOpen(false)} />
    </div>
  )
}
